#!/bin/bash

# This script sets up the basic environment for students enrolled in the course.

export OMP_NUM_THREADS=8

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m'

# Articulate what this program does
echo -e "\n\n${YELLOW}Welcome to the MAN 7916 launcher! This script will do the following:${NC}"
echo " * Create a MAN7916 folder in your home directory "
echo " * Create a Python virtual environment in that new folder"
echo " * Install Python packages into that virtual environment"
echo " * Load some needed files in the MAN7916 folder to help you complete the assignment"
echo -e "\nYou can always remove the artifacts created by this script by deleting the MAN7916 folder and its contents\n\n"

# Function to prompt the user
prompt_user() {
  echo -e "${GREEN}Do you want to continue? (Y/N):${NC} \c"
  read user_input
  case $user_input in
    [Yy]* )
      echo "Beginning installation. This may take a bit..."
      echo "=================================================="
      echo "========= Setting up directory and Python ========"
      echo "=================================================="
      module load cuda/cuda-12.6.0
      module load python/python-3.11.4-oneapi-2023.1.0
      echo "CUDA and Python modules loaded..."
      mkdir -p ~/MAN7916
      cp ./venv_and_directory_setup.slurm ~/MAN7916/venv_and_directory_setup.slurm
      cp ./man7916launcher ~/MAN7916/man7916launcher
      cp ./nltk_environ_setup.py ~/MAN7916/nltk_environ_setup.py
      cd ~/MAN7916
      touch __init__.py
      mkdir -p ./models
      mkdir -p ./output
      mkdir -p ./corpora
      echo "Directory structure created..."
      if [ ! -d ".venv" ]; then
	      python3 -m venv .venv
        echo "Virtual environment .venv created..."
      else
        echo "Virtual environment .venv already exists..."
      fi
      echo "Virtual environment activated..."
      echo ""
      echo "=================================================="
      echo "======= Downloading Text and Model Corpora ======="
      echo "============= This may take a while =============="
      echo "=================================================="

      TAR_FILE="./corpora/aclImdb_v1.tar.gz"
      EXTRACT_DIR="./corpora/aclImdb/"
      if [ ! -f "$TAR_FILE" ]; then
        echo "Downloading aclImdb_v1.tar.gz..."
        wget -q https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz -O "$TAR_FILE"
      else
        echo "File already exists: $TAR_FILE"
      fi

      if [ ! -d "$EXTRACT_DIR" ]; then
        echo "Extracting aclImdb_v1.tar.gz..."
        mkdir -p "$EXTRACT_DIR"
        tar -xzf "$TAR_FILE" -C "$EXTRACT_DIR" --strip-components=1
      else
        echo "Data already extracted in: $EXTRACT_DIR"
      fi

      UNSUP_DIR="./corpora/aclImdb/train/unsup/"

      if [ ! -d "$UNSUP_DIR" ]; then
        echo "unsup directory already removed... skipping..."
      else
        echo "Removing unneeded unsup directory: $UNSUP_DIR"
        rm -r "$UNSUP_DIR"
      fi

      sbatch ./venv_and_directory_setup.slurm
      echo "Done..."
      echo ""

      echo "========================================================="
      echo "The Python environment has been successfully set up."
      echo "The next thing that you need to do is to navigate to the "
      echo "created folder, request an interactive session, and "
      echo "run the Python files. To do this, you will need to run the "
      echo "following command (ignoring the *):"
      echo "* squeue -u <your username>"
      echo "(Replace <your username> with your username)"
      echo ""
      echo "If the displayed table has a row for you, wait a few minutes "
      echo "and run that line again - repeating until there is no row for "
      echo "you. That row is the remnants of this setup script."
      echo ""
      echo "When you have no row in the above command, run the following: "
      echo "* cd ~/MAN7916"
      echo "* module load cuda/cuda-12.6.0"
      echo "* module load python/python-3.11.4-oneapi-2023.1.0"
      echo "* source ./.venv/bin/activate"
      echo "* srun -p normal -t 0-01:00:00 --gres=gpu:1 --pty bash"
      echo "(You may have to wait a little bit, you just requested "
      echo "a compute node on Newton)"
      echo "* python3 run_sample_ml.py"
      echo ""
      echo "When you are done running the python code and are back to the "
      echo "command prompt, run the following command to release the "
      echo "compute node so that others can use it."
      echo "* exit"
      echo "========================================================="
      ;;
    [Nn]* )
      echo "You chose to exit. No changes will be made. Goodbye!"
      exit 0
      ;;
    * )
      echo "Invalid input. Please enter Y or N."
      prompt_user
      ;;
  esac
}

# Call the function
prompt_user

